name: labmon
recipe: laravel
config:
  webroot: public
  php: '8.2'
  cache: redis
services:
  mail:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  node:
    type: node:22
    ports:
      - 3009:3009
    build:
      - npm install
excludes:
  - node_modules
tooling:
  mfs:
    service: appserver
    description: "Drop db, migrate and seed"
    cmd: php artisan migrate:fresh && php artisan db:seed --class=TestDataSeeder
  horizon:
    service: appserver
    description: "Run horizon"
    cmd: php artisan horizon
  test:
    service: appserver
    description: "Run phpunit"
    cmd: CI=1 php artisan test --parallel
  testf:
    service: appserver
    description: "Run phpunit with --filter"
    cmd: php artisan test --filter
  fixldap:
    service: appserver
    description: "Set up insecure ldap"
    user: root
    cmd: apt-get update && apt-get install -y libldap-common && printf "\nTLS_REQCERT never\n" >> /etc/ldap/ldap.conf
  npm:
    service: node
    description: "Run npm command"
    cmd: npm
  npmd:
    service: node
    description: "Run npm run dev"
    cmd: npm run dev
  npmp:
    service: node
    description: "Run npm run build"
    cmd: npm run build
  npmw:
    service: node
    description: "Run npm run dev"
    cmd: npm run dev
